package com.socialapp.utils

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf

object Localization {
    private val EN = mapOf(
        "home_tab" to "Home",
        "training_tab" to "Training",
        "post_tab" to "Post",
        "chat_tab" to "Chat",
        "profile_tab" to "Profile",
        "search_hint" to "Search...",
        "quick_post_hint" to "What are you training today?",
        "create_story" to "Create Tin",
        "create_story_title" to "Create Story",
        "start_typing" to "Start typing...",
        "share" to "Share",
        "public" to "Public",
        "friends" to "Friends",
        "private" to "Private",
        "only_me" to "Only me",
        "followers" to "Followers",
        "following" to "Following",
        "edit_profile" to "Edit Profile",
        "gym_metrics_title" to "Gymer Metrics & Records (PR)",
        "update" to "Update",
        "height" to "Height",
        "weight" to "Weight",
        "body_fat" to "Body Fat",
        "bench_press" to "Bench Press",
        "squat" to "Squat",
        "deadlift" to "Deadlift",
        "ai_workout_btn" to "Generate AI Workout Plan",
        "ai_analyzing" to "AI is analyzing...",
        "posts" to "Posts",
        "saved" to "Saved",
        "no_posts" to "No posts yet",
        "no_saved_posts" to "No saved posts yet",
        "settings" to "Settings",
        "basic_settings" to "Basic Settings",
        "dark_mode" to "Dark Mode",
        "language" to "Language",
        "vietnamese" to "Vietnamese",
        "english" to "English",
        "private_account" to "Private Account",
        "change_language" to "Change Language",
        "cancel" to "Cancel",
        "notifications" to "Notifications",
        "no_notifications" to "No notifications yet",
        "mark_all_read" to "Mark all as read",
        "logout" to "Logout",
        "logout_confirm_title" to "Logout",
        "logout_confirm_desc" to "Are you sure you want to logout from the app?",
        "create_post_title" to "Create Post",
        "post_status_pending" to "Status: Pending",
        "post_btn" to "Post",
        "ai_suggest_tag" to "AI Suggest Tag",
        "ai_analyze_post" to "AI Analyze Post",
        "workout_log" to "Workout Log",
        "add_to_your_post" to "Add to your post",
        "tag_friends" to "Tag Friends",
        "done" to "Done",
        "comments" to "Comments",
        "write_comment" to "Write a comment...",
        "reply" to "Reply",
        "like" to "Like",
        "chat_list_title" to "Chats",
        "search_friends_hint" to "Search friends...",
        "friend_requests" to "Friend Requests",
        "accept" to "Accept",
        "no_chats" to "No conversations yet",
        "active_now" to "Active now",
        "training_center" to "Training Center",
        "muscle_plans" to "Muscle Plans",
        "daily_routines" to "Daily Routines",
        "ai_personal_plan" to "AI Personal Plan",
        "generate_ai_plan_btn" to "Generate Plan Now",
        "age" to "Age",
        "birthday" to "Birthday",
        "hometown" to "Hometown",
        "hobbies" to "Hobbies",
        "regime" to "Training Regime",
        "change_password" to "Change Password",
        "current_password" to "Current Password",
        "new_password" to "New Password",
        "confirm_password" to "Confirm Password",
        "success" to "Success!",
        "close" to "Close"
    )

    private val VI = mapOf(
        "home_tab" to "Trang chủ",
        "training_tab" to "Tập luyện",
        "post_tab" to "Đăng bài",
        "chat_tab" to "Trò chuyện",
        "profile_tab" to "Cá nhân",
        "search_hint" to "Tìm kiếm...",
        "quick_post_hint" to "Hôm nay bạn tập gì?",
        "create_story" to "Tạo tin",
        "create_story_title" to "Tạo tin mới",
        "start_typing" to "Bắt đầu nhập...",
        "share" to "Chia sẻ",
        "public" to "Công khai",
        "friends" to "Bạn bè",
        "private" to "Riêng tư",
        "only_me" to "Chỉ mình tôi",
        "followers" to "Người theo dõi",
        "following" to "Đang theo dõi",
        "edit_profile" to "Chỉnh sửa trang cá nhân",
        "gym_metrics_title" to "Chỉ số Gymer & Kỷ lục (PR)",
        "update" to "Cập nhật",
        "height" to "Chiều cao",
        "weight" to "Cân nặng",
        "body_fat" to "Tỉ lệ mỡ",
        "bench_press" to "Bench Press",
        "squat" to "Squat",
        "deadlift" to "Deadlift",
        "ai_workout_btn" to "Tạo Lịch Tập AI Cá Nhân",
        "ai_analyzing" to "AI đang phân tích...",
        "posts" to "Bài viết",
        "saved" to "Đã lưu",
        "no_posts" to "Chưa có bài viết nào",
        "no_saved_posts" to "Chưa có bài viết đã lưu nào",
        "settings" to "Cài đặt",
        "basic_settings" to "Cài đặt cơ bản",
        "dark_mode" to "Chế độ tối",
        "language" to "Ngôn ngữ",
        "vietnamese" to "Tiếng Việt",
        "english" to "Tiếng Anh",
        "private_account" to "Tài khoản riêng tư",
        "change_language" to "Thay đổi ngôn ngữ",
        "cancel" to "Hủy",
        "notifications" to "Thông báo",
        "no_notifications" to "Chưa có thông báo nào",
        "mark_all_read" to "Đánh dấu tất cả đã đọc",
        "logout" to "Đăng xuất",
        "logout_confirm_title" to "Đăng xuất",
        "logout_confirm_desc" to "Bạn có chắc chắn muốn đăng xuất khỏi ứng dụng không?",
        "create_post_title" to "Tạo bài viết",
        "post_status_pending" to "Trạng thái: Chờ duyệt",
        "post_btn" to "Đăng",
        "ai_suggest_tag" to "AI Gợi ý Tag",
        "ai_analyze_post" to "AI Phân tích bài",
        "workout_log" to "Nhật ký tập luyện",
        "add_to_your_post" to "Thêm vào bài viết của bạn",
        "tag_friends" to "Gắn thẻ bạn bè",
        "done" to "Xong",
        "comments" to "Bình luận",
        "write_comment" to "Viết bình luận...",
        "reply" to "Phản hồi",
        "like" to "Thích",
        "chat_list_title" to "Đoạn chat",
        "search_friends_hint" to "Tìm kiếm bạn bè...",
        "friend_requests" to "Lời mời kết bạn",
        "accept" to "Chấp nhận",
        "no_chats" to "Chưa có cuộc trò chuyện nào",
        "active_now" to "Đang hoạt động",
        "training_center" to "Trung tâm tập luyện",
        "muscle_plans" to "Lịch tập nhóm cơ",
        "daily_routines" to "Lịch trình hàng ngày",
        "ai_personal_plan" to "Lịch tập cá nhân AI",
        "generate_ai_plan_btn" to "Tạo Lịch Tập Ngay",
        "age" to "Tuổi",
        "birthday" to "Sinh nhật",
        "hometown" to "Quê quán",
        "hobbies" to "Sở thích",
        "regime" to "Chế độ tập luyện",
        "change_password" to "Đổi mật khẩu",
        "current_password" to "Mật khẩu hiện tại",
        "new_password" to "Mật khẩu mới",
        "confirm_password" to "Xác nhận mật khẩu",
        "success" to "Thành công!",
        "close" to "Đóng"
    )

    fun getString(key: String, lang: String): String {
        val map = if (lang == "en") EN else VI
        return map[key] ?: key
    }
}

val LocalLanguage = staticCompositionLocalOf { "vi" }

@Composable
fun t(key: String): String {
    val lang = LocalLanguage.current
    return Localization.getString(key, lang)
}