package com.socialapp.utils

import android.content.Context
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.platform.LocalContext

object Localization {
    private val EN = mapOf(
        "home" to "Home",
        "group" to "Group",
        "post" to "Post",
        "chat" to "Chat",
        "profile" to "Profile",
        "settings" to "Settings",
        "notifications" to "Notifications",
        "dark_mode" to "Dark Mode",
        "language" to "Language",
        "vietnamese" to "Vietnamese",
        "english" to "English",
        "premium" to "Premium",
        "premium_upgrade" to "Upgrade Premium",
        "private_account" to "Private Account",
        "basic_settings" to "Basic Settings",
        "workout_coach" to "AI Workout Coach",
        "generate_plan" to "Generate AI Workout Plan",
        "ai_analyzing" to "AI is analyzing...",
        "copy_plan" to "Copy Workout Plan",
        "plan_copied" to "Workout Plan Copied!",
        "posts" to "Posts",
        "saved" to "Saved",
        "create_story" to "Create Story",
        "text" to "Text",
        "music" to "Music",
        "no_posts" to "No posts yet",
        "no_saved_posts" to "No saved posts yet",
        "no_notifications" to "No notifications yet",
        "comments" to "Comments",
        "write_comment" to "Write a comment...",
        "change_password" to "Change Password",
        "current_password" to "Current Password",
        "new_password" to "New Password",
        "confirm_password" to "Confirm Password",
        "save" to "Save",
        "cancel" to "Cancel",
        "update" to "Update",
        "edit_profile" to "Edit Profile",
        "display_name" to "Display Name",
        "bio" to "Bio",
        "logout" to "Logout",
        "logout_confirm" to "Are you sure you want to logout?",
        "gym_metrics" to "Gymer Metrics & Records (PR)",
        "height" to "Height",
        "weight" to "Weight",
        "body_fat" to "Body Fat",
        "bench_press" to "Bench Press",
        "squat" to "Squat",
        "deadlift" to "Deadlift",
        "followers" to "Followers",
        "following" to "Following",
        "join" to "Join",
        "joined" to "Joined",
        "groups_title" to "Fitness Groups",
        "create_group" to "Create New Group",
        "group_name" to "Group Name",
        "group_desc" to "Group Description",
        "members" to "members",
        "create" to "Create",
        "select_music" to "Select Music Track",
        "change_language" to "Change Language",
        "premium_unlock_title" to "Unlock GymHub Premium",
        "premium_desc" to "Get access to all premium features and maximize your potential!",
        "premium_benefit_1" to "• Personalized AI workout generator based on your PRs",
        "premium_benefit_2" to "• Custom music stories & exclusive sharing filters",
        "premium_benefit_3" to "• Premium Golden Badge next to your profile username",
        "premium_benefit_4" to "• Dark Mode & early access to new fitness groups",
        "premium_price" to "Only $4.99 / month",
        "upgrade_now" to "Upgrade Now",
        "gymhub_premium" to "GymHub Premium",
        "mark_all_read" to "Mark all as read",
        "training_center" to "Training Center",
        "muscle_plans" to "Muscle Plans",
        "daily_routines" to "Daily Routines",
        "ai_personal_plan" to "AI Personal Plan",
        "generate_ai_plan_btn" to "Generate AI Plan",
        "regenerate_btn" to "Regenerate Plan",
        "ai_plan_desc" to "AI will design the most optimal training program based on your Gymer metrics from your Profile.",
        "ai_suggested_plan" to "AI Suggested Plan:",
        "copy_btn" to "Copy Plan",
        "copied_msg" to "Workout plan copied!",
        "show_more_info" to "Show More Profile Info",
        "show_less_info" to "Show Less Profile Info",
        "age" to "Age",
        "birthday" to "Birthday",
        "hometown" to "Hometown",
        "hobbies" to "Hobbies",
        "regime" to "Regime"
    )

    private val VI = mapOf(
        "home" to "Trang chủ",
        "group" to "Nhóm",
        "post" to "Đăng bài",
        "chat" to "Trò chuyện",
        "profile" to "Cá nhân",
        "settings" to "Cài đặt",
        "notifications" to "Thông báo",
        "dark_mode" to "Chế độ tối",
        "language" to "Ngôn ngữ",
        "vietnamese" to "Tiếng Việt",
        "english" to "Tiếng Anh",
        "premium" to "Premium",
        "premium_upgrade" to "Nâng cấp Premium",
        "private_account" to "Tài khoản riêng tư",
        "basic_settings" to "Cài đặt cơ bản",
        "workout_coach" to "Huấn luyện viên AI",
        "generate_plan" to "Tạo Lịch Tập AI cá nhân hóa",
        "ai_analyzing" to "AI đang phân tích...",
        "copy_plan" to "Sao chép lịch tập",
        "plan_copied" to "Đã sao chép lịch tập!",
        "posts" to "Bài viết",
        "saved" to "Đã lưu",
        "create_story" to "Tạo tin",
        "text" to "Văn bản",
        "music" to "Nhạc",
        "no_posts" to "Chưa có bài viết nào",
        "no_saved_posts" to "Chưa có bài viết đã lưu nào",
        "no_notifications" to "Chưa có thông báo nào",
        "comments" to "Bình luận",
        "write_comment" to "Viết bình luận...",
        "change_password" to "Đổi mật khẩu",
        "current_password" to "Mật khẩu hiện tại",
        "new_password" to "Mật khẩu mới",
        "confirm_password" to "Xác nhận mật khẩu",
        "save" to "Lưu",
        "cancel" to "Hủy",
        "update" to "Cập nhật",
        "edit_profile" to "Chỉnh sửa trang cá nhân",
        "display_name" to "Tên hiển thị",
        "bio" to "Tiểu sử",
        "logout" to "Đăng xuất",
        "logout_confirm" to "Bạn có chắc chắn muốn đăng xuất khỏi ứng dụng không?",
        "gym_metrics" to "Chỉ số Gymer & Kỷ lục (PR)",
        "height" to "Chiều cao",
        "weight" to "Cân nặng",
        "body_fat" to "Tỷ lệ mỡ",
        "bench_press" to "Bench Press",
        "squat" to "Squat",
        "deadlift" to "Deadlift",
        "followers" to "Người theo dõi",
        "following" to "Đang theo dõi",
        "join" to "Tham gia",
        "joined" to "Đã tham gia",
        "groups_title" to "Nhóm thể hình",
        "create_group" to "Tạo nhóm mới",
        "group_name" to "Tên nhóm",
        "group_desc" to "Mô tả nhóm",
        "members" to "thành viên",
        "create" to "Tạo",
        "select_music" to "Chọn bài hát",
        "change_language" to "Thay đổi ngôn ngữ",
        "premium_unlock_title" to "Mở khóa GymHub Premium",
        "premium_desc" to "Sử dụng toàn bộ tính năng cao cấp để bứt phá giới hạn bản thân!",
        "premium_benefit_1" to "• Tự động thiết kế lịch tập dựa trên chỉ số PR cá nhân",
        "premium_benefit_2" to "• Đăng tin kèm nhạc & kho bộ lọc chia sẻ độc quyền",
        "premium_benefit_3" to "• Huy hiệu tài khoản Vàng đặc biệt bên cạnh tên hiển thị",
        "premium_benefit_4" to "• Trải nghiệm Chế độ tối & ưu tiên tham gia các nhóm gym mới",
        "premium_price" to "Chỉ 109.000đ / tháng",
        "upgrade_now" to "Nâng cấp ngay",
        "gymhub_premium" to "GymHub Premium",
        "mark_all_read" to "Đánh dấu tất cả đã đọc",
        "training_center" to "Trung tâm tập luyện",
        "muscle_plans" to "Lịch tập nhóm cơ",
        "daily_routines" to "Lịch trình hàng ngày",
        "ai_personal_plan" to "Lịch tập cá nhân AI",
        "generate_ai_plan_btn" to "Tạo Lịch Tập AI",
        "regenerate_btn" to "Tạo Lại Lịch Tập",
        "ai_plan_desc" to "AI sẽ thiết kế lộ trình tập luyện tối ưu nhất dựa trên các chỉ số Gymer của bạn ở Profile.",
        "ai_suggested_plan" to "Lịch tập đề xuất từ AI:",
        "copy_btn" to "Sao chép lịch tập",
        "copied_msg" to "Đã sao chép lịch tập!",
        "show_more_info" to "Xem thêm thông tin cá nhân",
        "show_less_info" to "Thu gọn thông tin cá nhân",
        "age" to "Tuổi",
        "birthday" to "Ngày sinh",
        "hometown" to "Quê quán",
        "hobbies" to "Sở thích",
        "regime" to "Chế độ tập luyện"
    )

    fun getString(key: String, lang: String): String {
        val map = if (lang == "en") EN else VI
        return map[key] ?: (EN[key] ?: key)
    }
}

val LocalLanguage = staticCompositionLocalOf { "vi" }

@Composable
fun t(key: String): String {
    val lang = LocalLanguage.current
    return Localization.getString(key, lang)
}
